site_name: The Haskell Tool Stack
site_description: The Haskell Tool Stack
site_author: Stack contributors
repo_url: https://github.com/commercialhaskell/stack/
edit_uri: tree/stable/doc/
copyright: Copyright (c) 2015-2024, Stack contributors
docs_dir: doc
site_dir: _site
theme:
  name: material
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  icon:
    logo: material/language-haskell
  features:
  - content.code.copy
  - content.code.select
  - content.tabs.link
  - navigation.indexes
  - navigation.tabs
  - navigation.top
extra_css:
- css/extra.css
extra_javascript:
- js/searchhack.js
# Read the Docs requires JQuery for its JavaScript code to inject the flyout
# menu. Material for MkDocs does not come with JQuery.
- 'https://code.jquery.com/jquery-3.6.1.min.js'

nav:
- Welcome!: README.md
- Setting up: install_and_upgrade.md
- Getting started:
  - tutorial/index.md
  - 1. A Hello World example: tutorial/hello_world_example.md
  - 2. Building your project: tutorial/building_your_project.md
  - 3. Building existing projects: tutorial/building_existing_projects.md
  - 4. Installed package databases: tutorial/installed_package_databases.md
  - 5. stack build synonyms: tutorial/stack_build_synonyms.md
  - 6. stack build targets: tutorial/stack_build_targets.md
  - 7. Multi-package projects: tutorial/multi-package_projects.md
  - 8. Cabal flags and GHC options: tutorial/cabal_flags_and_ghc_options.md
  - 9. Locations used by Stack: tutorial/locations_used_by_stack.md
  - 10. Executing commands: tutorial/executing_commands.md
  - 11. Using GHC interactively: tutorial/using_ghc_interactively.md
  - 12. Stack configuration: tutorial/stack_configuration.md
  - 13. In conclusion: tutorial/tutorial_conclusion.md
- Commands:
  - commands/index.md
  - bench: commands/bench_command.md
  - build: commands/build_command.md
  - clean: commands/clean_command.md
  - config: commands/config_command.md
  - dot: commands/dot_command.md
  - docker: commands/docker_command.md
  - eval: commands/eval_command.md
  - exec: commands/exec_command.md
  - ghc: commands/ghc_command.md
  - ghci: commands/ghci_command.md
  - haddock: commands/haddock_command.md
  - hoogle: commands/hoogle_command.md
  - hpc: commands/hpc_command.md
  - ide: commands/ide_command.md
  - init: commands/init_command.md
  - install: commands/install_command.md
  - list: commands/list_command.md
  - ls: commands/ls_command.md
  - new: commands/new_command.md
  - path: commands/path_command.md
  - purge: commands/purge_command.md
  - query: commands/query_command.md
  - repl: commands/repl_command.md
  - run: commands/run_command.md
  - runghc: commands/runghc_command.md
  - runhaskell: commands/runhaskell_command.md
  - script: commands/script_command.md
  - sdist: commands/sdist_command.md
  - setup: commands/setup_command.md
  - templates: commands/templates_command.md
  - test: commands/test_command.md
  - uninstall: commands/uninstall_command.md
  - unpack: commands/unpack_command.md
  - update: commands/update_command.md
  - upgrade: commands/upgrade_command.md
  - upload: commands/upload_command.md
- Configure:
  - configure/index.md
  - Environment variables: configure/environment_variables.md
  - Configuration:
    - Introduction: configure/yaml/yaml_configuration.md
    - Project-specific: configure/yaml/project-specific_configuration.md
    - Non-project specific: configure/yaml/non-project_specific_configuration.md
  - Global flags and options: configure/global_flags.md
  - Customisation scripts: customisation_scripts.md
- Topics:
  - topics/index.md
  - Stack root: topics/stack_root.md
  - Stack work directories: topics/stack_work.md
  - Snapshot and package location: topics/pantry.md
  - Snapshot specification: topics/custom_snapshot.md
  - stack.yaml vs a Cabal file: topics/stack_yaml_vs_cabal_package_file.md
  - Script interpreter: topics/scripts.md
  - Docker integration: topics/docker_integration.md
  - Nix integration: topics/nix_integration.md
  - Non-standard project initialization: topics/nonstandard_project_init.md
  - Debugging: topics/debugging.md
  - Editor integration: topics/editor_integration.md
  - Stack and Visual Studio Code: topics/Stack_and_VS_Code.md
  - Developing on Windows: topics/developing_on_windows.md
  - Shell auto-completion: topics/shell_autocompletion.md
  - CI: topics/CI.md
  - Travis CI: topics/travis_ci.md
  - Azure CI: topics/azure_ci.md
  - Lock files: topics/lock_files.md
  - Haskell and C code: topics/haskell_and_c_code.md
- Get involved:
  - Contributors:
    - Contributor's guide: CONTRIBUTING.md
    - Dev Containers: dev_containers.md
  - Maintainers:
    - Releases: maintainers/releases.md
    - Maintainer team process: maintainers/team_process.md
    - Add GHC version: maintainers/ghc.md
    - Docker images: maintainers/docker.md
    - Upgrading MSYS2: maintainers/msys.md
    - Upgrading 7-Zip: maintainers/7zip.md
    - HaskellStack.org: maintainers/haskellstack.org.md
    - Self-hosted runners: maintainers/self-hosted_runners.md
    - Docker images: maintainers/docker_images.md
    - Signing key: SIGNING_KEY.md
  - How Stack works:
    - Build overview: build_overview.md
- FAQ: faq.md
- Glossary: glossary.md
- More:
  - Other resoruces: other_resources.md
  - Version history: ChangeLog.md

markdown_extensions:
- admonition
- attr_list
- def_list
- footnotes
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
