site_name: The Haskell Tool Stack
site_description: The Haskell Tool Stack
site_author: Stack contributors
repo_url: https://github.com/commercialhaskell/stack/
edit_uri: tree/stable/doc/
copyright: Copyright (c) 2015-2024, Stack contributors
docs_dir: doc
site_dir: _site
theme:
  name: material
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  icon:
    logo: material/language-haskell
  features:
  - content.code.copy
  - content.code.select
  - content.tabs.link
  - navigation.tabs
extra_css:
- css/extra.css
extra_javascript:
- js/searchhack.js
# Read the Docs requires JQuery for its JavaScript code to inject the flyout
# menu. Material for MkDocs does not come with JQuery.
- 'https://code.jquery.com/jquery-3.6.1.min.js'

nav:
- Welcome!: README.md
- Setup: install_and_upgrade.md
- Getting started: GUIDE.md
- Commands:
  - commands/index.md
  - bench command: commands/bench_command.md
  - build command: commands/build_command.md
  - clean command: commands/clean_command.md
  - config commands: commands/config_command.md
  - dot command: commands/dot_command.md
  - docker commands: commands/docker_command.md
  - eval command: commands/eval_command.md
  - exec command: commands/exec_command.md
  - ghc command: commands/ghc_command.md
  - ghci command: commands/ghci_command.md
  - haddock command: commands/build_command.md
  - hoogle command: commands/hoogle_command.md
  - hpc command: commands/hpc_command.md
  - ide command: commands/ide_command.md
  - init command: commands/init_command.md
  - install command: commands/build_command.md
  - list command: commands/list_command.md
  - ls command: commands/ls_command.md
  - new command: commands/new_command.md
  - path command: commands/path_command.md
  - purge command: commands/purge_command.md
  - query command: commands/query_command.md
  - repl command: commands/ghci_command.md
  - run command: commands/run_command.md
  - runghc command: commands/runghc_command.md
  - runhaskell command: commands/runghc_command.md
  - script command: commands/script_command.md
  - sdist command: commands/sdist_command.md
  - setup command: commands/setup_command.md
  - templates command: commands/templates_command.md
  - test command: commands/build_command.md
  - uninstall command: commands/uninstall_command.md
  - unpack command: commands/unpack_command.md
  - update command: commands/update_command.md
  - upgrade command: commands/upgrade_command.md
  - upload command: commands/upload_command.md
- Configure:
  - configuration_introduction.md
  - Environment variables: environment_variables.md
  - Configuration (project and global): yaml_configuration.md
  - Global flags and options: global_flags.md
- Topics:
  - Stack root: stack_root.md
  - Stack work directories: stack_work.md
  - Snapshot and package location: pantry.md
  - Snapshot specification: custom_snapshot.md
  - stack.yaml vs a Cabal file: stack_yaml_vs_cabal_package_file.md
  - Script interpreter: scripts.md
  - Docker integration: docker_integration.md
  - Nix integration: nix_integration.md
  - Non-standard project initialization: nonstandard_project_init.md
  - Debugging: debugging.md
  - Editor integration: editor_integration.md
  - Stack and Visual Studio Code: Stack_and_VS_Code.md
  - Developing on Windows: developing_on_windows.md
  - Shell auto-completion: shell_autocompletion.md
  - CI: CI.md
  - Travis CI: travis_ci.md
  - Azure CI: azure_ci.md
  - Lock files: lock_files.md
  - Haskell and C code: haskell_and_c_code.md
- Get involved:
  - Contributors:
    - Contributor's guide: CONTRIBUTING.md
    - Dev Containers: dev_containers.md
  - Maintainers:
    - Releases: maintainers/releases.md
    - Maintainer team process: maintainers/team_process.md
    - Add GHC version: maintainers/ghc.md
    - Docker images: maintainers/docker.md
    - Upgrading MSYS2: maintainers/msys.md
    - Upgrading 7-Zip: maintainers/7zip.md
    - HaskellStack.org: maintainers/haskellstack.org.md
    - Self-hosted runners: maintainers/self-hosted_runners.md
    - Docker images: maintainers/docker_images.md
    - Signing key: SIGNING_KEY.md
  - How Stack works:
    - Build overview: build_overview.md
- FAQ: faq.md
- Glossary: glossary.md
- More:
  - Other resoruces: other_resources.md
  - Version history: ChangeLog.md

markdown_extensions:
- admonition
- attr_list
- footnotes
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
