snapshot: lts-24.0 # GHC 9.10.2

extra-deps:
# lts-24.0 specifies pantry-0.10.1
- pantry-0.11.0@sha256:d23aad04f560280264bde7a8d20ed158a668c037c303dc00793d8af61176c491,7542

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.10.2

# See LICENSE. In order to build a statically-linked Stack executable for Linux
# that is not linked against GMP, use this alternative Docker image:
# repo: quay.io/benz0li/ghc-musl:9.10.2-int-native

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
