resolver: lts-22.0 # GHC 9.6.3

extra-deps:
# Cabal is pruned because process is a GHC boot package, and has to be specified
# again.
- Cabal-3.10.1.0@sha256:6d11adf7847d9734e7b02785ff831b5a0d11536bfbcefd6634b2b08411c63c94,12316
# GHC 9.6.3 comes with process-1.6.17.0, which can segfault on macOS.
- process-1.6.18.0@sha256:cd0a3e0376b5a8525983d3131a31e52f9ffefc278ce635eec45a9d3987b8be3e,3025
# lts-22.0 specifies rio-prettyprint-0.1.7.0:
- rio-prettyprint-0.1.8.0@sha256:28a034bfa2842043d4603800e47943027677746cca0b3b8088aee10168870105,1428

docker:
  enable: false
  repo: glcr.b-data.ch/ghc/ghc-musl:9.6.3

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  hackage-security:
    cabal-syntax: true
  stack:
    developer-mode: true
