snapshot: lts-22.21 # GHC 9.6.5

extra-deps:
# lts-22.21 provides pantry-0.9.3.2.
- pantry-0.10.0@sha256:6f99ee8d7cfeeb0e2513638618acf80c72d018e7f10120048fa120a409b9dcd2,7864
# lts-22.21 provides tar-0.5.1.1, which does not support Unicode filenames:
- tar-0.6.2.0@sha256:619828cae098a7b6deeb0316e12f55011101d88f756787ed024ceedb81cf1eba,4576

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.6.5

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
