snapshot: lts-23.17 # GHC 9.8.4

extra-deps:
# lts-23.17 provides hpack-0.37.0
- hpack-0.38.1@rev:0
# lts-23.17 provides pantry-0.10.0.
- pantry-0.10.1@rev:0
# lts-23.17 provides tls-2.1.1
- tls-2.1.8@rev:0

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.8.4
# See LICENSE. In order to build a statically-linked Stack executable for Linux
# that is not linked against GMP, use this alternative Docker image:
# repo: quay.io/benz0li/ghc-musl:9.8.4-int-native

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
