snapshot: lts-23.0 # GHC 9.8.4

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.8.4

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
