snapshot: lts-24.4 # GHC 9.10.2

extra-deps:
# lts-24.4 specifies Cabal-3.12.1.0
- Cabal-syntax-3.16.0.0
- Cabal-3.16.0.0
# lts-24.4 specifies hpack-0.38.1@rev:0
- hpack-0.38.1@sha256:609ea3a56fb4c1a37c24935e1bd31d64bbd6e44c527470adb7c2cc2bee35cd37,5457
# lts-24.4 specifies pantry-0.10.1
- pantry-0.11.0@sha256:2dd0fd7e08f9c1464a993e288cba1128479f79e4b0c7977e5c1c26a68941127e,7911

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.10.2

# See LICENSE. In order to build a statically-linked Stack executable for Linux
# that is not linked against GMP, use this alternative Docker image:
# repo: quay.io/benz0li/ghc-musl:9.10.2-int-native

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
